# Introduction

Application: minimum least squares to estimate demographic parameters for populations.

## Defining a null matrix

In [13]:
#
x <- c(1,1)

#
n <- length(x)

#
k <- 5

#
res <- matrix(0, ncol = k * n, nrow = k)

#
res

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 0    0    0    0    0    0    0    0    0    0    
[2,] 0    0    0    0    0    0    0    0    0    0    
[3,] 0    0    0    0    0    0    0    0    0    0    
[4,] 0    0    0    0    0    0    0    0    0    0    
[5,] 0    0    0    0    0    0    0    0    0    0

In [8]:
for (i in 1:k){
  res[i,((i - 1)*n + 1):(i*n)] <- x
  }

res

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 1    1    0    0    0    0    0    0    0    0    
[2,] 0    0    1    1    0    0    0    0    0    0    
[3,] 0    0    0    0    1    1    0    0    0    0    
[4,] 0    0    0    0    0    0    1    1    0    0    
[5,] 0    0    0    0    0    0    0    0    1    1

## Defining a matrix

In [9]:
A <- t(c(1,1))

A

[,1] [,2]
[1,] 1    1

## Kronecker product

In mathematics, the Kronecker product, sometimes denoted by ⊗, is an operation on two matrices of arbitrary size resulting in a block matrix. It is a generalization of the outer product (which is denoted by the same symbol) from vectors to matrices, and gives the matrix of the tensor product linear map with respect to a standard choice of basis. The Kronecker product is to be distinguished from the usual matrix multiplication, which is an entirely different operation. The Kronecker product is also sometimes called matrix direct product.

**References**

* [Kronecker_product](https://en.wikipedia.org/wiki/Kronecker_product)

In [10]:
diag(10) %x% A

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    1    0    0    0    0    0    0    0    0     0     0     0    
 [2,] 0    0    1    1    0    0    0    0    0    0     0     0     0    
 [3,] 0    0    0    0    1    1    0    0    0    0     0     0     0    
 [4,] 0    0    0    0    0    0    1    1    0    0     0     0     0    
 [5,] 0    0    0    0    0    0    0    0    1    1     0     0     0    
 [6,] 0    0    0    0    0    0    0    0    0    0     1     1     0    
 [7,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
 [8,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
 [9,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[10,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20]
 [1,] 0     0     0     0     0     0     0    
 [2,] 0     0     0     0     0     0     0    
 [3,] 0     0     0     0     0     0     0    
 [4,] 0     0     0     0     0     0     0    
 [5,] 0     0     0     0     0     0     0    
 [6,] 0     0     0     0     0     0     0    
 [7,] 1     0     0     0     0     0     0    
 [8,] 0     1     1     0     0     0     0    
 [9,] 0     0     0     1     1     0     0    
[10,] 0     0     0     0     0     1     1